networks:
  extern-net:
  silk-auth-net:

volumes:
  pgdata:

x-app-environment: &app-environment
  DATABASE_URL: postgres://${POSTGRES_USER:-silkauth}:${POSTGRES_PASSWORD:-silkauth}@database:5432/${POSTGRES_DB:-silkauth_dev}
  NODE_ENV: development

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-silkauth}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-silkauth}
      POSTGRES_DB: ${POSTGRES_DB:-silkauth_dev}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-silkauth} -d ${POSTGRES_DB:-silkauth_dev}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      silk-auth-net:
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT:-3001}:80"
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.host}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    profiles:
      - develop
    networks:
      silk-auth-net:

  app:
    build:
      context: .
      target: devrunner
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${DEV_APP_PORT:-3000}:3000"
    volumes:
      - ./:/app
      - ./dev_modules/app/node_modules:/app/node_modules
      - ./dev_modules/app/.next:/app/.next
      - ./dev_modules/pnpm_store:/app/.pnpm-store
    environment:
      <<: *app-environment
    networks:
      extern-net:
      silk-auth-net:

  app-shell:
    build:
      context: .
      target: devrunner
    command: /bin/bash
    depends_on:
      - app
    volumes_from:
      - app
    environment:
      <<: *app-environment
    profiles:
      - shell
    networks:
      silk-auth-net:
